version: '3.7'

services:
  crate:
    image: crate:3.3 # Please check release notes!
    hostname: crate
    networks:
        - fiware
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      #- "4300:4300"
    networks:
      - fiware
    command: crate -Clicense.enterprise=false -Cauth.host_based.enabled=false -Ccluster.name=fiwaredemo -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    volumes:
      - crate:/data/db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  fiware:
    driver: overlay
volumes:
  crate: