version: '3.7'

services:
  boundarycondition:
    image: registry.git.rwth-aachen.de/ebc/team_bes/hil/hil_infrastructure_python/test_boundarycondition:1.5
    environment:
      - START_TIME=0
      - END_TIME=540
      - TIME_STEP=1
      - WITH_REALTIME=True
      - WITH_OUTPUT=True 
      - API_KEY=xsn1gs10dnmwkl3
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 50m

# networks:
# boundarycondition_net:
  # external: true

# configs:
# base.env:
  # external: true