version: '3.7'

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
        - fiware
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  fiware:
    driver: overlay